name: my_Epam_CD
env:
  REGION: "eu-central-1"
  SSH_USER: "root"
  
on:
  push:
    branches:
    - main

jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
    - name: copy my html on Runner
      uses: actions/checkout@v3

    - name: view my html
      run: ls -l

    - name: init AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.REGION }}

    - name: get EC2 PublicIP
      run: |
        echo "PUBLICIP=$(aws ec2 describe-instances \
        --filters 'Name=private-ip-address,Values=172.31.23.10' \
        --query 'Reservations[*].Instances[*].PublicIpAddress' \
        --output text)" >> $GITHUB_ENV

    - name: print PublicIP
      run: echo ${{ env.PUBLICIP }}

    - name: establish SSH connection
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "${{ secrets.SSH_FRANKFURT_KEY }}" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa

    - name: deploy my html
      run: |
        scp -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -r ./* ${{ env.SSH_USER }}@${{ env.PUBLICIP }}:/opt/pyapp/

    - name: restart docker my-pyapp
      run: |
        ssh -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            ${{ env.SSH_USER }}@${{ env.PUBLICIP }} \
            "docker restart my-pyapp"
